module.exports = {
    NOT_FOUND_HTTP_CODE: 404,
    BAD_REQUEST_HTTP_CODE: 400,
    INTERNAL_ERROR_HTTP_CODE: 500,
    OK_HTTP_CODE: 200,
    CREATED_HTTP_CODE: 204,
    NOT_AUTHORIZED_HTTP_CODE: 401,
}